"""
run.py -- emit the SAP arm's results.

    python3 run.py > RESULTS_SAP.md

Machine-generated, like every other results artefact in this project, so prose
cannot quietly disagree with the code.
"""
from __future__ import annotations

from sapsec.experiments import (CompanionTestbedMissing, book_stack, x7, x8,
                                x9, x11, x12)
from sapsec.workload import (FRAUD_N, HIGH, LEGIT_N, LOW, MATERIALITY)


def pct(x: float) -> str:
    return "%.1f%%" % (100 * x)


def main():
    r7, r8, r9 = x7(), x8(), x9()
    r11, r12 = x11(), x12()
    try:
        bs = book_stack()
    except CompanionTestbedMissing as exc:
        bs = None
        bs_missing = str(exc)
    p, c, b = r7["primary"], r7["control"], r7["budget"]

    print("# The SAP arm — results")
    print()
    print("*Generated by `python3 run.py`. Do not edit by hand.*")
    print()
    print("Pre-registered in `PREREG_SAP.md` before any of this existed. "
          "Every authorisation mechanism below was reconstructed from "
          "secondary sources: at the time these experiments were registered "
          "and run, the automated retrieval route had not yielded the required "
          "SAP documentation and no primary vendor material had been "
          "incorporated. **These are results about that reconstruction, and "
          "that remains permanently true of them.** The project's current "
          "evidence state is tracked separately in `PREREG_SAP.md` and has "
          "since advanced; see loss L3 and determination D1.")
    print()

    # -- X7 ---------------------------------------------------------------
    print("## X7 — the missing rate limiter")
    print()
    print("**Result: the pre-registered WEAKENING outcome.** The claim as "
          "written — that a per-step model *cannot express* a constraint on "
          "outcome — is too strong and is withdrawn. What replaces it is "
          "smaller and sharper.")
    print()
    print("### Setup")
    print()
    print("| | |")
    print("|:---|:---|")
    print("| legitimate workload | %d customer credit memos, company code "
          "1000, document type DG, amounts %.0f–%.0f |" % (LEGIT_N, LOW, HIGH))
    print("| harmful sequence | %d further memos, **same distribution, same "
          "company code, same document type, same activity** |"
          % FRAUD_N)
    print("| difference between them | count, and nothing else — enforced in "
          "code by `assert_indistinguishable()` |")
    print("| harm predicate | cumulative credited value in the period exceeds "
          "materiality (%.0f), read from the ledger |" % MATERIALITY)
    print("| configuration space | %d points: activity, company code, document "
          "type authorisation group, per-document tolerance, per-line "
          "tolerance |" % p.n_configs)
    print()
    print("The tolerance dimensions matter. FI tolerance groups are the "
          "strongest value-based per-step control in the modelled surface, "
          "and they are "
          "included precisely so the claim could lose.")
    print()
    print("### The sweep")
    print()
    print("| | value |")
    print("|:---|---:|")
    print("| configurations evaluated | %d |" % p.n_configs)
    print("| configurations that keep the outcome below materiality | %d |"
          % p.n_prevent_harm)
    print("| best legitimate throughput among those | **%s** |"
          % pct(p.best_legit_fraction))
    print("| clean separation (≥95%% throughput retained) | **%s** |"
          % ("yes" if p.clean_separation else "no"))
    print("| legitimate value per period | %.0f |" % p.legit_total)
    print("| value posted in the attacked session, unconstrained | %.0f |"
          % p.unconstrained_harm)
    print()
    print("Ten thousand configurations hold the outcome below materiality. "
          "Every one of them does it by refusing between three-fifths and all "
          "of the legitimate work. The best configuration found — per-document "
          "tolerance 3,000 — keeps %s of the business running."
          % pct(p.best_legit_fraction))
    print()
    print("### Sensitivity to the one number we chose")
    print()
    print("Materiality is the only figure here that was picked rather than "
          "measured, so the result is reported as a function of it.")
    print()
    print("| materiality | as a share of the attacked session | best "
          "legitimate throughput |")
    print("|---:|---:|---:|")
    for m, frac, ratio in r7["curve"]:
        print("| %.0f | %s | %s |" % (m, pct(ratio), pct(frac)))
    print()
    print("The two right-hand columns track each other to within the "
          "granularity of the amount grid. That is the finding, and it is "
          "structural rather than numerical:")
    print()
    print("> **Because the harmful and legitimate documents are "
          "indistinguishable per document, any per-document predicate removes "
          "the same proportion of each. The per-step surface can buy a "
          "reduction in the harm only by buying an equal reduction in the "
          "work. The exchange rate is one to one.**")
    print()
    print("So the authorisation model *can* bound the outcome. It bounds it "
          "the way a fuse bounds a fire. What it cannot do is discriminate, "
          "and discrimination is the entire content of the word *control*.")
    print()

    # -- instrument check --------------------------------------------------
    print("### Instrument check (positive control)")
    print()
    print("Pre-registered. The same sweep, against a harmful sequence whose "
          "amounts lie entirely above the legitimate band, **must** find a "
          "separating tolerance. If it cannot, the sweep is broken and the "
          "primary result means nothing.")
    print()
    print("| | value |")
    print("|:---|---:|")
    print("| configurations that prevent the harm | %d |" % c.n_prevent_harm)
    print("| best legitimate throughput among those | **%s** |"
          % pct(c.best_legit_fraction))
    print("| clean separation | **%s** |"
          % ("yes" if c.clean_separation else "no"))
    print()
    print("`%s`" % c.best_config)
    print()
    print("The instrument works. When a per-document difference exists, the "
          "sweep finds it and loses nothing. The primary arm's failure is "
          "therefore about the primary arm, not about the method.")
    print()

    # -- the repair --------------------------------------------------------
    print("### The repair, and what it costs")
    print()
    print("A cumulative per-principal budget over the period is not "
          "expressible in the modelled surface. Added as a separate control "
          "and run through identical machinery:")
    print()
    print("| | value |")
    print("|:---|---:|")
    print("| budget settings tested | %d |" % b.n_configs)
    print("| that prevent the harm | %d |" % b.n_prevent_harm)
    print("| legitimate throughput under normal operation | **%s** |"
          % pct(b.best_legit_fraction))
    print("| legitimate documents posted **during the attacked session** | "
          "**%d of %d** |" % (r7["budget_legit_posted"],
                              r7["budget_legit_total"]))
    print()
    print("This is the part a vendor slide would omit. Under normal operation "
          "the budget is invisible: full throughput, no friction. Under attack "
          "it works — and it works by spending itself on whatever arrives "
          "first, so %d of %d legitimate documents are refused as collateral. "
          "The control converts a silent aggregate fraud into a loud partial "
          "outage. That is a better failure, and it is still a failure, and an "
          "architect deciding whether to deploy it deserves to be told which "
          "one they are buying."
          % (r7["budget_legit_total"] - r7["budget_legit_posted"],
             r7["budget_legit_total"]))
    print()

    # -- book stack --------------------------------------------------------
    print("### Does the generic agent-security stack close it?")
    print()
    print("No. The same session, run through the book's own testbed with every "
          "one of its controls enabled — strict egress, verb scope, resource "
          "scope, payload-visible approval, descriptor pinning, memory "
          "provenance, ephemeral credentials, signed-head audit, "
          "information-flow labelling, sink-side DLP, memory quarantine, "
          "external baseline:")
    print()
    if bs is not None:
        print("| | value |")
        print("|:---|---:|")
        print("| calls attempted | %d |" % bs["n"])
        print("| executed | **%d** |" % bs["executed"])
        print("| blocked | **%d** |" % bs["blocked"])
        print("| value posted | %.0f |" % bs["value_posted"])
        print()
        print("Every control fires on a property of the individual action. "
              "None of them holds a counter. This is not a criticism of the "
              "stack that would be unfair to make of published guidance either "
              "— it is the same absence, found in our own work, which is the "
              "only reason it is worth reporting.")
        print()
    else:
        print("> *The numeric cross-check is not reproduced in this build: %s "
              "No figure is printed here rather than a fabricated one. Every "
              "control in that stack fires on a property of the individual "
              "action and none of them holds a counter, which is why the "
              "generic stack does not close this path — the same absence, "
              "found in our own work.*" % bs_missing)
        print()

    # -- X8 ---------------------------------------------------------------
    print("## X8 — composed authority across propagated principals")
    print()
    print("**Result: the claim holds, and the interesting finding is not the "
          "one that was pre-registered.**")
    print()
    print("| principal | Access Risk Analysis |")
    print("|:---|:---|")
    for u, v in r8["ara"].items():
        print("| `%s` (propagated) | %s |" % (u, "clean" if not v
                                              else ", ".join(v)))
    print("| `RFC_AGENT` (technical user holding both grants) | %s |"
          % ", ".join(r8["tech_violations"]))
    print()
    print("The agent alters a vendor's bank details in one session under one "
          "human's propagated identity, and executes the payment run in a "
          "second session under another's. Each principal is individually "
          "clean. The payment reaches the attacker's account: `%s`."
          % r8["payments"][0]["iban"])
    print()
    print("Two things must be said about this before it is allowed to sound "
          "like a discovery.")
    print()
    print("First, it is close to definitional. A static predicate over grants "
          "cannot see a composition across grants; that follows from the word "
          "*static*. The pre-registered instrument check confirms the harm is "
          "real and pre-existing — two colluding humans produce it identically "
          "(**%s**) — which means agents introduce no new harm here. What they "
          "change is the price. Collusion requires two people to agree. "
          "Composition requires one agent to have been given both sessions, "
          "and nobody has to agree to anything."
          % ("confirmed" if r8["collusion_harm"] else "NOT confirmed"))
    print()
    print("Second, and this is the part worth the chapter: **the safer-looking "
          "architecture is the one that defeats the analysis.** Principal "
          "propagation — the design secondary material attributes to Joule, "
          "and the one "
          "any reviewer would prefer, because it means the agent holds no "
          "standing authority of its own — produces two individually clean "
          "principals and an invisible composition. The technical user, which "
          "looks worse on every checklist because it accumulates grants, is "
          "the one Access Risk Analysis can see. The control rewards the "
          "architecture that gives it something to look at.")
    print()

    # -- X9 ---------------------------------------------------------------
    print("## X9 — attribution")
    print()
    print("**Pre-registered as definitional. Reported as definitional.** It is "
          "in the register so that its status was fixed before the numbers "
          "made it tempting to call it a finding.")
    print()
    print("| | value |")
    print("|:---|---:|")
    print("| log records written | %d |" % r9["n"])
    print("| actions attributable to an actor, as logged | **%d** |"
          % r9["attributed_without"])
    print("| ...with one additional field | **%d** |" % r9["attributed_with"])
    print()
    print("A record identifies a principal. Under principal propagation the "
          "principal is the human. The record correctly identifies the "
          "authenticated principal but carries no separate identity for the "
          "autonomous process that selected the action. If the principal field "
          "is interpreted as naming the decider rather than the accountable "
          "principal, the selection is consequently assigned to the named "
          "employee.")
    print()
    print("The repair is one field. The value of this experiment is entirely "
          "in that sentence, and it may not be used to support X7 or X8.")
    print()

    # -- X11 --------------------------------------------------------------
    print()
    print("## X11 — the transport-governance surface")
    print()
    print("**Result: the pre-registered WEAKENING outcome, and the third "
          "branch as well.** The standing prediction P1 held at the pair it "
          "names and is narrowed by the same experiment that confirmed it.")
    print()
    print("P1 predicted that release authorisation cannot discriminate a "
          "harmful transport. The specification-sensitivity audit ruled that "
          "prediction misspecified — release authorisation never claimed "
          "behavioural safety — and required it respecified against the whole "
          "governance surface before it could be run. This is that "
          "experiment.")
    print()
    print("### The surface")
    print()
    print("| step | ranges over | placement | enforced by |")
    print("|:---|:---|:---|:---|")
    for st in r11["steps"]:
        print("| **%s** %s | %s | %s | %s |"
              % (st.id, st.name, st.ranges_over, st.placement, st.enforced_by))
    print()
    print("### Setup")
    print()
    print("| | |")
    print("|:---|:---|")
    print("| legitimate arm | %d transports, benign objects |" % r11["n_arm"])
    print("| harmful arm | %d transports carrying a change to an FI "
          "validation exit that stops the tolerance predicate firing |"
          % r11["n_arm"])
    print("| difference between them | what an object does once active, and "
          "nothing else — same owner, target, request class, object types and "
          "object count, enforced by `assert_transport_indistinguishable()` |")
    print("| harm predicate | a harmful object active in production |")
    print("| configuration space | %s points: which of the six steps are "
          "switched on, whether the static-check catalogue contains a rule "
          "for this harm class, human review coverage, quality-system test "
          "coverage, and the rate at which a content step stops a BENIGN "
          "transport |" % "{:,}".format(r11["n_configs"]))
    print()
    print("The harmful behaviour attacks this paper's own principal finding. "
          "If it reaches production the tolerance control measured in X7 stops "
          "firing, which is the least self-serving harm available to us.")
    print()
    print("**On the false-positive rate.** The first version of this "
          "experiment had no such parameter, so a content-ranging step was a "
          "perfect oracle: it stopped every harmful transport and no "
          "legitimate one, in every configuration. That produced a striking "
          "table which this section reported as a measured contrast against "
          "X7, and it was a property of the construction. It is loss L6. The "
          "parameter is now swept across four values and **none of them is "
          "measured** — no claim below rests on any particular one.")
    print()
    print("### The sweep")
    print()
    print("| | value |")
    print("|:---|---:|")
    print("| configurations evaluated | %s |"
          % "{:,}".format(r11["n_configs"]))
    print("| configurations that discriminate (harm stopped, ≥95%% of "
          "legitimate transports retained) | %s |"
          % "{:,}".format(r11["n_discriminating"]))
    print("| ...that stop discriminating if the static catalogue does not "
          "carry the harm | %s |" % "{:,}".format(r11["needs_catalogue"]))
    print("| configurations whose active steps range only over the REQUEST | "
          "%d |" % r11["n_request_only"])
    print("| ...that discriminate | **%d** |"
          % r11["request_only_discriminating"])
    print("| ...harmful transports reaching production in the best of them | "
          "**%d of %d** |" % (r11["request_only_harm_in_prd"], r11["n_arm"]))
    print("| configurations whose only content-ranging step is DETECTIVE | "
          "%d |" % r11["n_detective_only"])
    print("| ...that discriminate | **%d** |"
          % r11["detective_only_discriminating"])
    print()
    print("Positive control: %s — in %d configurations with release "
          "authorisation active and a principal lacking `S_TRANSPRT ACTVT "
          "43`, every transport was refused."
          % ("passed" if r11["control_ok"] else "**FAILED**", r11["n_control"]))
    print()
    print("### Where the prediction narrows")
    print()
    print("| minimal content-ranging preventive steps | configurations | "
          "needs the catalogue | minimum review coverage | minimum test "
          "coverage |")
    print("|:---|---:|:---|---:|---:|")
    for key in sorted(r11["minimal"], key=lambda k: (len(k), k)):
        rec = r11["minimal"][key]
        print("| %s | %d | %s | %s | %s |"
              % (", ".join(key), rec["n"],
                 "yes" if rec["needs_atc"] else "no",
                 ("%.0f%%" % (100 * rec["min_review"])),
                 ("%.0f%%" % (100 * rec["min_test"]))))
    print()
    print("The surface contains decisions that range over the property's own "
          "subject, so the prediction narrows: the mismatch is real at the "
          "authorisation object and is covered elsewhere in the same surface. "
          "That is a control-placement finding of the same shape as "
          "Availability Control, and transport leaves the list of open "
          "mismatches.")
    print()
    print("### Three things the sweep says that the narrowing does not")
    print()
    print("**Coverage is a parameter, not a guarantee.** With the static "
          "catalogue assumed not to contain a rule for this harm class, human "
          "review is the only preventive content decision left, and the harm "
          "reaching production falls linearly with how much of the change "
          "somebody reads:")
    print()
    print("| review coverage | harmful transports in production |")
    print("|---:|---:|")
    for cov, harm, _lf in r11["curve"]:
        print("| %.0f%% | %d of %d |" % (100 * cov, harm, r11["n_arm"]))
    print()
    print("**What it costs is not a property of the pair.** This is the point "
          "the first version of this experiment got wrong. In X7 the price of "
          "reducing harm is forced: the two workloads are per-document "
          "identical, so every per-document predicate removes the same "
          "proportion of each and no configuration escapes the one-to-one "
          "exchange. Here the price is not forced by the control-property "
          "pair at all. It is whatever the content decision's false-positive "
          "rate happens to be, and the model neither measures that rate nor "
          "can.")
    print()
    print("| a content step stops this share of benign transports | "
          "configurations | of which discriminate | legitimate throughput |")
    print("|---:|---:|---:|---:|")
    for fp, n, nd, lo, hi in r11["fp_cost"]:
        print("| %.0f%% | %s | %s | %.0f–%.0f%% |"
              % (100 * fp, "{:,}".format(n), "{:,}".format(nd),
                 100 * lo, 100 * hi))
    print()
    print("At a five percent false-positive rate the surface still meets the "
          "95% bar X7 was held to. At ten percent nothing does. **So the "
          "honest form of the contrast is not that one control is cheap and "
          "the other expensive.** It is that an extent mismatch makes the "
          "exchange rate a property of the control-property pair, which no "
          "implementation can improve, while a subject match makes it a "
          "property of the implementation, which a bad one can squander. That "
          "is a smaller claim than the one this section carried a day ago and "
          "it is the one the evidence supports.")
    print()
    print("**Detection is not prevention, and the surface separates them "
          "cleanly.** In the configurations whose only content-ranging step "
          "runs after the import, %d of %d harmful transports are flagged and "
          "%d of %d are in production. Perfect detection, zero prevention. "
          "The paper has not had to make that distinction anywhere else and "
          "now has to make it here."
          % (r11["detective"]["flagged"], r11["n_arm"],
             r11["detective"]["in_prd"], r11["n_arm"]))
    print()
    print("**What this is not.** Whether SAP's delivered check variants "
          "contain a rule matching this harm class is not answered here. It "
          "is swept as a parameter and reported on both branches: on the "
          "branch where the catalogue does not carry it, %s of %s "
          "configurations still discriminate, and every one of them does so "
          "through a human step whose coverage nothing enforces."
          % ("{:,}".format(r11["n_no_atc_discriminating"]),
             "{:,}".format(r11["n_no_atc"])))
    print()

    # -- X12 --------------------------------------------------------------
    print()
    print("## X12 — attribution from correlates")
    print()
    print("**Result: the pre-registered STRENGTHENING outcome.** This is the "
          "experiment loss L2 records as pre-declared and never run, and it "
          "tests the half of the principle that is not about extent: the "
          "claim that a non-injective subject map is a projection failure "
          "rather than a memory failure.")
    print()
    print("### Setup")
    print()
    print("| | |")
    print("|:---|:---|")
    print("| session | %d actions by k concurrent actors behind one "
          "propagated principal |" % r12["n_actions"])
    print("| swept | actor count, interleaved or serialised, clock resolution, "
          "whether the terminal names the actor, whether the transaction code "
          "does, idle gap between serialised blocks, and how many preceding "
          "records the responder may hold |")
    print("| conditions | %d, of which %d have more than one actor |"
          % (r12["n_conditions"], r12["n_multi"]))
    print("| responder | partitions by the fields that name an origin, then "
          "splits on temporal discontinuity where the retained gaps are "
          "bimodal; scored on its best possible relabelling |")
    print()
    print("Positive control: %s — every one of the %d single-actor conditions "
          "attributed perfectly (worst %.3f). A procedure that cannot name the "
          "actor when there is one candidate would make the rest meaningless."
          % ("passed" if r12["control_ok"] else "**FAILED**",
             r12["n_control"], r12["control_worst"]))
    print()
    print("### Does retained history repair it?")
    print()
    print("| actors | retention 1 | 10 | 100 | whole period |")
    print("|---:|---:|---:|---:|---:|")
    for k in (2, 4, 8):
        row = [a for (kk, _r, a) in r12["baseline"] if kk == k]
        print("| %d | %.3f | %.3f | %.3f | %.3f |" % (k, *row))
    print()
    print("Those are the conditions principal propagation actually produces: "
          "one technical user, one terminal, one transaction code, actions "
          "interleaved, whole-second stamps. Accuracy is exactly 1/k and "
          "exactly flat. Across all %d condition groups, retention changed the "
          "outcome in %d of them — and in **%d of the %d groups where no "
          "recorded field separated the actors, retention changed nothing at "
          "all**. The best accuracy reached anywhere in those groups is %.3f, "
          "which is chance."
          % (r12["n_groups"], r12["n_moved_by_retention"],
             r12["n_no_signal_moved"], r12["n_no_signal"],
             r12["no_signal_best"]))
    print()
    print("So retention does help — in %d groups it moved the result "
          "materially — and in every one of those a separating field was "
          "already present for it to exploit. Retention improves how well an "
          "existing signal is used. It does not create one. That is the "
          "clause the formalism makes, stated more precisely than the "
          "formalism stated it."
          % r12["n_moved_by_retention"])
    print()
    print("| how the %d successful conditions succeeded | count |"
          % r12["n_good"])
    print("|:---|---:|")
    for reason, n in r12["by_reason"].items():
        print("| %s | %d |" % (reason, n))
    print()
    print("### The bound, and the practitioner's objection")
    print()
    print("A procedure that fails is weak evidence; the reply is always that a "
          "better one would have worked. So the primary instrument is not a "
          "procedure. Two records carrying identical observable fields are the "
          "same record to any procedure, which must answer the same for both. "
          "The best achievable accuracy is therefore fixed by the evidence "
          "rather than by anyone's cleverness — and loss L4 records why that "
          "matters here.")
    print()
    print("| actors | upper bound on any procedure | majority baseline | ours |")
    print("|---:|---:|---:|---:|")
    for k, b, m, a in r12["bounds"]:
        print("| %d | %.3f | %.3f | %.3f |" % (k, b, m, a))
    print()
    print("The bound sits above what our procedure achieved, so we do not "
          "claim it is optimal. It also sits far below one.")
    print()
    print("The objection G3 actually has to answer is different and blunter: "
          "*an agent posting hundreds of documents in minutes is obviously not "
          "a person, and you never checked.* One human and one agent, same "
          "principal, same terminal, same transaction code, with the agent's "
          "action rate swept:")
    print()
    print("| agent posts every | records | upper bound on any procedure | "
          "majority baseline | machine-speed activity detected |")
    print("|---:|---:|---:|---:|:---|")
    for r in r12["rate"]:
        print("| %.3fs | %d | %.4f | %.4f | %s |"
              % (r["interval"], r["n"], r["bound"], r["majority"],
                 "yes" if r["presence"] else "no"))
    print()
    print("The bound equals the majority baseline at every rate, to four "
          "decimal places. No procedure reading principal, transaction code, "
          "terminal and timestamp can attribute a single action better than "
          "answering *the busiest actor* for every record without reading "
          "anything at all. **The practitioner is right that you can tell an "
          "agent was there, and wrong that this attributes the action.** The "
          "density signal is a presence test, and the last column is honest "
          "about its own weakness: it fires in all six rows, including the two "
          "where neither actor exceeds human speed, so it is detecting "
          "aggregate load rather than machine speed.")
    print()
    print("What survives is a bound over one modelled evidence stream. Change "
          "documents, table logging and read-access logging were not modelled, "
          "and a correlate in any of them would narrow this further.")
    print()


if __name__ == "__main__":
    main()
